version: '3.8'

services:
  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8080:8080"   # Spring Boot default port
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/quiz_app_dev
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quiz_app_dev
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
