version: '3.8'

services:
  api:
    build: .
    ports:
      - "7000:7000"
    environment:
      - API_VERSION=v1
      - JWT_SECRET=${JWT_SECRET}
      - JWT_ACCESS_EXPIRATION=${JWT_ACCESS_EXPIRATION}
      - JWT_REFRESH_EXPIRATION=${JWT_REFRESH_EXPIRATION}
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
      - DATABASE_URL=${DATABASE_URL}
    volumes:
      - ./app:/app/app
    restart: unless-stopped
